name: PR Pipeline
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
env:
  nuget-username: chrisxpr
  src-dir: ./src/code
  coverage-threshold: 10
  repo-organisation: architected
  team-pat: ${{ secrets.NUGET_PAT}}
concurrency: alpha-${{ github.ref}}
jobs:
  dotnetBuild:
    name: Build and Test
    runs-on: ubuntu-latest
    environment: dev
    timeout-minutes: 20
    steps:
      - name: Checkout action
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: buildAndTest
        uses: devperimental/composite-action-library/dotnet-build-and-test@v2
        with:
          nuget-username: ${{ env.nuget-username }}
          src-dir: ${{ env.src-dir }}
          coverage-threshold: ${{ env.coverage-threshold }}
          repo-organisation: ${{ env.repo-organisation }}
          team-pat: ${{ env.team-pat }}
